/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e0e0ff",
        "on-secondary": "#ffffff",
        "secondary-container": "#959efd",
        "on-primary-container": "#f4fffb",
        "on-surface": "#191c1d",
        "on-tertiary-fixed-variant": "#354a53",
        "on-tertiary-container": "#fbfdff",
        "surface-container": "#eceeef",
        "primary-container": "#008376",
        "on-primary-fixed-variant": "#005048",
        "secondary-fixed-dim": "#bdc2ff",
        "on-secondary-fixed-variant": "#343d96",
        "on-primary-fixed": "#00201c",
        "tertiary-fixed-dim": "#b4cad6",
        "surface": "#f8fafb",
        "surface-bright": "#f8fafb",
        "on-secondary-container": "#27308a",
        "error": "#ba1a1a",
        "tertiary-fixed": "#cfe6f2",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f2",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006b5f",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#70d8c8",
        "on-tertiary-fixed": "#071e27",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#000767",
        "surface-container-low": "#f2f4f5",
        "primary-fixed": "#8df5e4",
        "outline": "#6d7a77",
        "tertiary-container": "#627882",
        "on-background": "#191c1d",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadb",
        "primary": "#00685d",
        "tertiary": "#4a5f69",
        "surface-variant": "#e1e3e4",
        "background": "#f8fafb",
        "surface-container-high": "#e6e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface-variant": "#3d4946",
        "secondary": "#4c56af",
        "inverse-primary": "#70d8c8",
        "inverse-surface": "#2e3132",
        "outline-variant": "#bcc9c5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "margin-page": "48px",
        "container-max": "1280px",
        "gutter": "24px",
        "stack-md": "16px",
        "section-padding": "80px"
      },
      fontFamily: {
        "sans": ["Public Sans", "sans-serif"],
        "h3": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "label-caps": ["Public Sans"],
        "h1": ["Public Sans"],
        "body-md": ["Public Sans"],
        "h2": ["Public Sans"]
      },
      fontSize: {
        "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "h1": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
